### PR TITLE
Include optional dependencies from dtscalibration dependencies

### PR DESCRIPTION
**Pull request by bdestombe**
Use "xarray[parallel,accel]" instead of filling up the dtscalibration dependency list with optional xarray dependencies.

### CODE REVIEW

**Comment by BSchilperoort** [comment]
I see your branch is out of date. Want to first handle off #187 and then redo this PR? 😇

**Comment by bdestombe** [comment]
> I see your branch is out of date. Want to first handle off #187 and then redo this PR? 😇

Sure! No rush

**Comment by BSchilperoort** [comment]
It would make for a cleaner commit (just a single commit to `main`, by using the `rebase and merge` option) if you would create a new branch from main and redo the changes on there.

Seeing as we directly import from dask, I would leave that a direct dependency. Same for pandas. Things we don't directly import (flox) can be installed with the extras options for xarray.

**Review by BSchilperoort — APPROVED** [review]
Looks good to me

**Pull request merged**
