### PR TITLE
Modernize project setup

### PR DESCRIPTION
**Pull request by BSchilperoort**
To do:
- [x] Move configs to pyproject.toml
- [x] Move package building to hatch
- [x] Set up hatch scripts to replace old linters (using ruff)
- [x] Integrate docs rendering into sphinx, add failure check
- [x] Update changelog, add @klapo to contributors
- [x] Bump version to 1.2.0 (in preparation of release)

### CODE REVIEW

**Comment by BSchilperoort** [comment]
@klapo could you review this pull request? I have updated the build system, scripts and instructions. Now it should be easier to keep the CI and local tests in sync (instead of using tox).

I also updated the changelog (in preparation of a new release), and added you as a contributor.

**Comment by bdestombe** [comment]
Is the wiki on releasing a new version still correct after these changes?

**Comment by BSchilperoort** [comment]
Ah, I forgot about the wiki. However, I shouldn't update that before merging these changes.
Alternatively, I could add a dev-readme file, which is easier to keep in sync with changes.

**Comment by bdestombe** [comment]
Rerunning the tests on this branch will probably fail. Let's merge #166 before and rebase accordingly.

**Review by bdestombe — APPROVED** [review]
Great work! This is a great overhaul and greatly reduces the code base. Two comments:

- A short note on releasing a new version would be very useful. Like you mentioned, in a separate file within the repository. And remove the wiki, as we are not using it.
- I wasn't able to fully review the notebooks. The diffs didn't work well because they also changed directory. Did you make any changes to the notebooks? In #157, I did make some big changes to the notebooks. In case you made changes we should take care merging/rebasing #157 .
- Great to have Klapo onboard! Thanks for your contribution!

**Comment by klapo** [comment]
Thanks for acknowledging me, but I haven't really done much :see_no_evil:! But, I am happily using your fantastic code. I'll run it through our automated set up in the next few weeks to make sure nothing is wonky that wasn't caught in the testing.

**Comment by klapo** [comment]
Oh! I see I was even mentioned and asked to review. Sorry for not being more on top of things. Do you still want me to take a review anything?

**Comment by BSchilperoort** [comment]
> Thanks for acknowledging me, but I haven't really done much see_no_evil! But, I am happily using your fantastic code. I'll run it through our automated set up in the next few weeks to make sure nothing is wonky that wasn't caught in the testing.

> Oh! I see I was even mentioned and asked to review. Sorry for not being more on top of things. Do you still want me to take a review anything?

Well you did pick up fixing the numpy issue ;)
The review shouldn't be needed anymore, unless you're interested in how the project is now set up. This PR doesn't change any functionality, so I hope it runs fine. PR #157 will make some breaking changes, and will be accompanied by a major version bump (2.0).

> Great work! This is a great overhaul and greatly reduces the code base. Two comments:
> 
>     * A short note on releasing a new version would be very useful. Like you mentioned, in a separate file within the repository. And remove the wiki, as we are not using it.
> 
>     * I wasn't able to fully review the notebooks. The diffs didn't work well because they also changed directory. Did you make any changes to the notebooks? In [Linear error propagation #157](https://github.com/dtscalibration/python-dts-calibration/pull/157), I did make some big changes to the notebooks. In case you made changes we should take care merging/rebasing [Linear error propagation #157](https://github.com/dtscalibration/python-dts-calibration/pull/157) .

Thanks for the review. I can write up a small dev-readme about the release workflow.

The notebooks stayed the same, except that I cleared all output cells. The notebooks should be committed clean (no output or metadata), which makes for small and clear diffs. By rendering them for the docs it also tests them for errors. 
As you made big changes to the notebooks, you just clean their outputs and move them to the new folder.

**Comment by bdestombe** [comment]
Ready to merge?

**Pull request merged**
