### PR TITLE
Linear error propagation

### PR DESCRIPTION
**Pull request by bdestombe**
- [x] Linear error propagation for double-ended calibration
   - [x] Initial code
   - [x] Tests
   - [x] Example notebooks
 - [x] Linear error propagation for single-ended calibration
   - [x] Initial code
   - [x] Tests
   - [x] Example notebooks
 - [x] Remove OLS
   - [x] Examples
   - [x] Code
 - [x] Bump major version

### CODE REVIEW

**Comment by BSchilperoort** [comment]
Nice, let me know if you have any questions about the CI.

**Comment by bdestombe** [comment]
@BSchilperoort Are you okay with removing OLS? I don't see any use cases for OLS anymore, as the calibration results are worse and there is barely a gain in computation speed.

**Comment by bdestombe** [comment]
Furthermore, this branch will break will break with the current dev branch.

**Comment by BSchilperoort** [comment]
> @BSchilperoort Are you okay with removing OLS? I don't see any use cases for OLS anymore, as the calibration results are worse and there is barely a gain in computation speed.

I think it would be OK. It would probably be nicer to have if it's not too much work. There could be edge cases where people would like to have it, or to actually be able to demonstrate why WLS is nicer.

> Furthermore, this branch will break will break with the current dev branch. So we would also need to bump the major version.

It would be good if you could merge main back into this branch.

Additionally, I made PR #164 recently, which modernizes the project setup (using pyproject.toml to configure the package, uses ruff, etc.). It would be nice if we can merge that into `main` before this branch. I don't see too many possible merge conflicts either, so it should not be too complex.

**Comment by bdestombe** [comment]
All tests run fine on my computer. Would rebasing this brach with main resolve the failing tests? As far as I can see, the failures are not a result from code that I have changed..

**Comment by bdestombe** [comment]
@BSchilperoort I'm having some difficulties with running the test notebook function on Windows. That function makes use of Python's `tempfile.NamedTemporaryFile` and it returns an permission error only on Windows. Im not entirely sure on what's going on, as I don't have a Windows machine at my disposal. Is this something you witnessed before? Can you help me out with this one? This also causes the main branch to fail.

**Comment by bdestombe** [comment]
> @BSchilperoort I'm having some difficulties with running the test notebook function on Windows. That function makes use of Python's `tempfile.NamedTemporaryFile` and it returns an permission error only on Windows. Im not entirely sure on what's going on, as I don't have a Windows machine at my disposal. Is this something you witnessed before? Can you help me out with this one? This also causes the main branch to fail.

Solved! This issue is also causing the other branches to crash

**Comment by BSchilperoort** [comment]
> > @BSchilperoort I'm having some difficulties with running the test notebook function on Windows. That function makes use of Python's `tempfile.NamedTemporaryFile` and it returns an permission error only on Windows. Im not entirely sure on what's going on, as I don't have a Windows machine at my disposal. Is this something you witnessed before? Can you help me out with this one? This also causes the main branch to fail.
> 
> Solved! This issue is also causing the other branches to crash

Nice that you solved it. If you want to use temporary files in tests, it's best to use pytest's framework for that. https://docs.pytest.org/en/7.1.x/how-to/tmp_path.html

However, testing the notebooks is included in #164 already (through the docs rendering), so I am not sure if we want to do it twice. I feel like it should me more of a check that the notebooks are still up to date with the code, rather than using the notebooks as unit tests.

**Comment by bdestombe** [comment]
@BSchilperoort What do you think?

**Pull request merged**
